### ISSUE TITLE
Better way to detect systemd-network presence

### ISSUE THREAD

**Issue by ibukanov** [gsauthof/dracut-sshd#16]
The depends function checks for presence of systemd-networkd using:
```
 -L /etc/systemd/system/multi-user.target.wants/systemd-networkd.service
```

This misses the case when systemd-networkd is enabled via drop-in config file in multi-user.target.d or via a systemd generator with a link under /run/systemd.

The code should instead use systemctl -q is-enabled systemd-networkd or perhaps just check for the presence of systemd-networkd binary.

**Comment by gsauthof** [comment]
Using `systemctl -q is-enabled` is a good idea.

Just checking for the systemd-networkd binary is problematic because of cases where the binary is available but unused. Then it would just increase the size of the initramfs since root configures initrd network by other means (e.g. via the ifcfg module).

Looking at the code I'm unsure if the network dependency is a good choice. I mean perhaps systemd-networkd is disabled but root still wants to use systemd-networkd in early-boot. In that case the network dependency would be superfluously increase the initramfs size, too.

If systemd-networkd is enabled then the systemd-networkd dependency probably makes sense in most cases. But perhaps there is a minority case where early boot should still use a different network method.

Perhaps it would make sense to just remove those dependencies and let the user decide what to include for networking during early userspace?

**Comment by ibukanov** [comment]
Removing dependencies sounds suits me better. I have an installation script that writes /etc/dracut.conf.d where I can include the necessary dependencies. On the other hand it implies an extra configuration step during install for people who do have systemd-networkd running.

So as a conservative change I suggest to check for `systemctl -q is-active systemd-networkd` (not is-enabled as that may not cover all cases of systemd-networkd activation).

**Comment by gsauthof** [comment]
Ok, I've removed the dependency logic now.
