### ISSUE TITLE
GPL 2 licensing

### ISSUE THREAD

**Issue by artem-sidorenko** [gsauthof/dracut-sshd#3]
Hi Georg,

you mentioned somewhere, you would like to see that module upstream by dracut. Within README.md you mention that this work is licensed under 'GPLv3+'. Dracut [is licensed under GPLv2](https://github.com/dracutdevs/dracut/blob/master/COPYING). In this case [this is a bit problematic](https://opensource.stackexchange.com/questions/1777/why-is-gplv2-incompatible-with-gplv3).

May I ask you to relicense your work under 'GPLv2' to get it compatible with dracut?
(and can you please add the License file and according steps required by GPLv2 too?)

Many thanks!
Artem

/cc @rbu

**Comment by gsauthof** [comment]
I'll reopen this issue if a **member** of the Dracut project sees the current license as a blocker for integration of this dracut-sshd module into Dracut upstream.

Since dracut is currently distributed under 'GPLv2+ and LGPLv2+' I doubt that a license change will be requested by the upstream dracut team, though.

Just for the record, artem-sidorenko doesn't represent the Dracut team, he just maintains the out-of-tree Dracut module 'dracut-crypt-ssh'.

I have no obligation to respond to each and every overly long and meandering email of his.
