### ISSUE TITLE
/var/sshd doesn't get created on Ubuntu 20.04

### ISSUE THREAD

**Issue by 8times4** [gsauthof/dracut-sshd#45]
Hey @gsauthof , 

I'm trying to get this to work on Ubuntu 20.04, and ssh server keep failing to start.
![image](https://user-images.githubusercontent.com/46720448/110127396-e2adc380-7dc5-11eb-82db-057268024df9.png)
If I create a folder myself in /var/sshd with 0755, it'll start right away, but I have to make that change manually. 

Any idea how could I solve this? 

Thanks, 
Mark

**Comment by gsauthof** [comment]
You mean you manually add `/var/sshd` to the initramfs archive? Which Ubuntu's sshd then uses as privilege separation directory?

The module script already contains some logic to detect the distribution specific privilege separation directory:

https://github.com/gsauthof/dracut-sshd/blob/3ba5a809ec56c667e51a5806edcf263b9d5ad250/46sshd/module-setup.sh#L70-L82

That means that code checks what's available in the running system to see what's required in the early-boot environment.

Does Ubuntu deviates from Debian in that point and uses `/var/sshd` as privilege escalation directory instead of `/run/sshd` (in the standard environment)? If yes, then we could add that location to that test loop.

**Comment by gsauthof** [comment]
Ok, I installed Ubuntu 20.04 in a VM and checked it myself. Ubuntu definitely uses `/run/sshd ` and **not** `/var/sshd `, i.e. sshd uses the same privilege separation directory as on Debian.

This is what sshd logged in the early boot environment, on that Ubuntu VM:

```
Jul 17 15:16:10 u2004 sshd[440]: Missing privilege separation directory: /run/sshd
```

So the root cause is that Ubuntu - in contrast to other distributions - fails to copy the `/run` content from the initramfs to the tmpfs `/run` mount point.

I thus added code such that the privilege separation directory is created via the systemd tmpfiles mechanism, as well.
