### ISSUE TITLE
Does this module support OpenSSH Certificates?

### ISSUE THREAD

**Issue by w4tsn** [gsauthof/dracut-sshd#48]
I'm interested to allow a range of backup admins with their [OpenSSH Certificates](https://blog.habets.se/2011/07/OpenSSH-certificates.html) from our infrastructure. This is not stated in the README so I'm wondering, does dracut-sshd support this?

Such certificates would allow to handle the access control to initramfs rescue shell with issuing and revocation of certificates for the individuals ssh keys.

**Comment by gsauthof** [comment]
I haven't configured OpenSSH with certs, so far. However, since dracut-sshd includes the distributions `sshd` it should work. Modulo some extra configuration. Meaning that you would need to add some extra dracut config such that your certificates are copied into the initramfs and you would need to adjust `46sshd/sshd_config` to enable ssh client and/or server cert-auth.

I guess, it would be possible that sshd needs some extra shared libraries for cert authentication. Then you would include those, as well. But should be straight forward to test in a VM.

**Comment by champtar** [comment]
If you add your ssh ca in /root/.ssh/authorized_keys as `cert-authority,principals="aaa" ssh-...` it should already work IMO

**Comment by gsauthof** [comment]
Ok, I'm closing this since the original request was answered. Feel free to reopen it or create a new issue in case something needs to be changed in dracut-sshd.

**Comment by w4tsn** [comment]
I can confirm that adding a `cert-authority` line to the `authorized_keys` file included in dracut just works. I had missed out that adding a cert authority that way was an option. I only used the `/etc/ssh/sshd_config` option so far.

Thanks for the help @champtar and @gsauthof !
