### ISSUE TITLE
Aligning with dracut-crypt-ssh?

### ISSUE THREAD

**Issue by dm17** [gsauthof/dracut-sshd#50]
Inspired by this thread: https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

What do the dracut-sshd maintainers think of this? The main difference I see off the bat, which I require, is the ability to use it on systems without systemD. Perhaps work can be deduplicated? What would the challenges be? I notice that more people are watching & have stared [dracut-crypt-ssh](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh) than [dracut-sshd](https://github.com/gsauthof/dracut-sshd) on GitHub - despite not being updated for years.

Thanks for your great work!

**Comment by gsauthof** [comment]
dacut-sshd creator and maintainer here.

I don't see how any work is duplicated as the dracut-crypt-ssh project is very inactive during the last years.

I don't have any plans to support non-systemd systems with dracut-sshd and I won't accept any pull-requests for such a support.

By design, every dracut-sshd feature was carefully evaluated to avoid adding unnecessary complexity. You know, every new feature is a trade-off: more functionality but also more complexity. And more complexity increases testing efforts, maintenance efforts, increases the chance of bugs and regressions, increases the efforts for reviewing the security of this module etc.

Thus, and since a solution for a non-systemd system wouldn't share that much with dracut-sshd anyways, I recommend to support non-systemd system in an independent project.

Regarding the number of stars: I wouldn't read too much into it. dracut-crypt-ssh is longer around, thus it had more time to accumulate them ([see also](https://seladb.github.io/StarTrack-js/#/preload?r=dracut-crypt-ssh,dracut-crypt-ssh&r=gsauthof,dracut-sshd)). Of course, there isn't necessarily a correlation between number of stars and number of active users. I mean, some people use starring just as a form of bookmarking. Or, if you lose interest in something/you don't use something anymore you don't necessary remove your star.

See also https://github.com/gsauthof/dracut-sshd#related-work where I reviewed several alternatives, including non-systemd and even non-dracut ones. Especially the initramfs hooks listed on the linked ArchWiki page might be of interest to you and perhaps already solve your non-systemd use-case.

**Comment by sotiris-bos** [comment]
I have been using this tool for years and has been amazing with my encrypted-root-on-zfs setup.

However, after recent Grub changes, many of us encrypted root zfs users have resorted to switching to ZFSBootmenu instead. ZfsBootmenu uses dracut to create either an initramfs image or a unified Efi image and is incompatible with systemd.

Zfsbootmenu creators have been promoting dracut-crypt-ssh use for remote management since it is compatible with non-systemd-enabled initramfs images, a module that has seen minimal updates in years and doesn't even work in some cases, such as mine.

I see a great value of forking or modifying this tool so that it can be used with non-systemd initramfs systems, such as ZFSBootmenu, if anyone capable of doing so reads this.
