### ISSUE TITLE
OpenSUSE Leap 15.3 - can't connect to host

### ISSUE THREAD

**Issue by ghost** [gsauthof/dracut-sshd#57]
Hi there,

I had this setup working previously on a host with OpenSUSE Tumbleweed. I just needed to setup another computer with OpenSUSE Leap 15.3 and followed the very same instructions. I copied the files to `/usr/lib/dracut/modules.d`, in `/etc/systemd/network` and in `/etc/dracut.conf.d`. Ran `sudo zypper install systemd-network` and `sudo dracut -f -vcs`. I have the authorized_keys file in all 3 folders mentioned on the page.

After rebooting I only get:
```
ssh: connect to host 192.168.178.100 port 22: Connection refused
```

**Comment by gsauthof** [comment]
Have you tried to debug this?

cf. last entry under: https://github.com/gsauthof/dracut-sshd#faq

**Comment by s-a-p-i-e-n-s** [comment]
No, I have not. Thank you for the patience, I resorted to using Tumbleweed for now, but will try to debug this in a VM soonish.

**Comment by gsauthof** [comment]
Perhaps this was also caused by the systemd-tmpfiles-setup service ordering setting that is now changed:

https://github.com/gsauthof/dracut-sshd/commit/aadea55dc8c1da0f329ecd63064487b7346d973d

Thus, if you want you can retest it with the current master version.

**Comment by gsauthof** [comment]
FWIW, I've installed openSUSE Leap 15.5 in a VM and I was surprised that dracut-sshd is already packaged for it!

I've tried it first with the legacy network scripts like this:

```
# cat /etc/dracut.conf.d/90-network.conf 
add_dracutmodules+=" network "
```

However, this alone isn't sufficient to get network during early boot, i.e. at the point of early-boot sshd start and before and after the luks-unlock prompt is displayed, the network interface isn't configured, yet.

FWIW, the entropy at that point is sufficient and the VM specific `virtio-rng-pci` device is automatically detected.

---

However, after `zypper install systemd-network` and setting the network up as described in the dracut-sshd README Install Section, network connectivity was properly configured in early boot, such that I could successfully unlock the root device via ssh.

All this worked with the distribution provided package:

```
# zypper info dracut-sshd
Loading repository data...
Reading installed packages...


Information for package dracut-sshd:
------------------------------------
Repository     : openSUSE-Leap-15.5-1
Name           : dracut-sshd
Version        : 0.6.1-2.34
Arch           : noarch
Vendor         : SUSE LLC <https://www.suse.com/>
Installed Size : 22.1 KiB
Installed      : Yes
Status         : up-to-date
Source package : dracut-sshd-0.6.1-2.34.src
Upstream URL   : https://github.com/gsauthof/dracut-sshd
Summary        : Provide SSH access to initramfs early user space
```

---

I also tested latest and greatest dracut-ssh from the master git branch and everything continues to work fine:


```
$ ssh  -p 10023 root@localhost

Welcome to the early boot SSH environment. You may type

    systemd-tty-ask-password-agent

(or press "arrow up") to unlock your disks.

This shell will terminate automatically a few seconds after the
unlocking process has succeeded and when the boot proceeds.

initramfs-ssh:/root# uname -a
Linux localhost 5.14.21-150500.53-default #1 SMP PREEMPT_DYNAMIC Wed May 10 07:56:26 UTC 2023 (b630043) x86_64 x86_64 x86_64 GNU/Linux
initramfs-ssh:/root# systemd-tty-ask-password-agent
🔐 Please enter passphrase for disk QEMU_HARDDISK (cr_root): *************           
initramfs-ssh:/root# Connection to localhost closed by remote host.
Connection to localhost closed.
```

---

Additional things to note:

openSUSE Leap 15.5 server doesn't install NetworkManager nor Systemd networkd, by default.
Instead, legacy network scripts are set up, which work out of the box (for normal boot).
This is interesting, because those (or similar) network scripts were deprecated in RHEL8 and removed in RHEL9.

When selecting disk encryption in the default openSUSE Leap GUI installer, it also encrypts /boot, by default. Thus, during boot, one has to unlock the disk two times! And the first time from grub, i.e. before early boot!

This is due to /boot being created as a Btrfs subvolume as part of the same Btrfs volume that resides on a LUKS device, by default.

Of course, for remote unlocking with just dracut-sshd, one has to take care that /boot is created on a separate partition that isn't encrypted.

---

Feel free to open another issue if you still run into problems with current dracut-ssh and current openSUSE Leap and you want to share additional information.

**Comment by d03j** [comment]
> When selecting disk encryption in the default openSUSE Leap GUI installer, it also encrypts /boot, by default. Thus, during boot, one has to unlock the disk two times! And the first time from grub, i.e. before early boot!

That does not seem to be the case with 15.6, whole disk encryption, LVM and btrfs: you only have to enter the decryption password once, before grub comes up.

> Of course, for remote unlocking with just dracut-sshd, one has to take care that /boot is created on a separate partition that isn't encrypted.

Is that openSUSE-specific or dues to /boot being encrypted? is there any way for dracut-sshd to work with full disk encryption?

Sorry if this is a silly question - I learned everything I know about linux by tinkering with ubuntu. I am new to openSUSE and ever had any reason to look into the booting process until now that I'm trying to get dracut-sshd to work.

**Comment by gsauthof** [comment]
> > Of course, for remote unlocking with just dracut-sshd, one has to take care that /boot is created on a separate partition that isn't encrypted.
> 
> Is that openSUSE-specific or dues to /boot being encrypted?

The latter.

>  is there any way for dracut-sshd to work with full disk encryption?

No, there isn't, because dracut-sshd is stored inside the initramfs file which is located on `/boot`.
Thus, if `/boot` is encrypted the early boot environment (and thus dracut-sshd) can't be loaded before somebody or something unlocks `/boot` first ...

**Comment by d03j** [comment]
thanks for this. I thought it was the case. I managed to make it work by creating a separate /boot partition  and everything else in a n encrypted partition with an LVM. it works as it should.
