### ISSUE TITLE
Why did you set "PermitRootLogin yes"?

### ISSUE THREAD

**Issue by cryptomilk** [gsauthof/dracut-sshd#6]
Hi,

I'm looking into this with @danimo. I wonder why you set PermitRootLogin yes. For safety reasons I would only permit publickey auth.

**Comment by gsauthof** [comment]
Actually, the config **does** only permit public-key authentication because it also sets:

    AuthenticationMethods           publickey

I set `PermitRootLogin yes` because I explicitly want to permit root to login - although just with a public-key.

That said, since the [PermitRootLogin is specified to default][1] to `prohibit-password` (on Fedora 30) that default is actually a better fit.

Perhaps when I wrote the config I only recalled the `yes`/`no` values for the `PermitRootLogin` option and possibly assumed a default of `no`.

Thus, if sshd behaves as described I'll change the line to:

    PermitRootLogin prohibit-password

It's tempting to just delete it, but since [CentOS 7 has a different default][2], i.e. `yes` the explicit setting still makes sense.

[1]: https://manpath.be/f30/5/sshd_config#L776
[2]: https://manpath.be/c7/5/sshd_config#L739
